// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGOnboardingTool.Infrastructure.Data;

#nullable disable

namespace RPGOnboardingTool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250713005440_ConfigureCharacterRowVersion")]
    partial class ConfigureCharacterRowVersion : Migration // Ensure it inherits from Migration  
    {
        /// <inheritdoc />  
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Existing code  
        }
        // Implement the Up method to fix the CS0534 error
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add migration logic here
        }

        // Implement the Down method to ensure the migration can be reverted
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Add logic to revert the migration here
        }
    }
}
