// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGOnboardingTool.Infrastructure.Data;

#nullable disable

namespace RPGOnboardingTool.Infrastructure.Migrations
{
    // Ensure that the class AddRowVersionToCharacter inherits from a class that has the BuildTargetModel method to override
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250713003547_AddRowVersionToCharacter")]public partial class AddRowVersionToCharacter : Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Existing code
        }

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Implement the logic for the migration here
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Implement the logic to revert the migration here
        }
    }
}
